### ISSUE TITLE
[ Formatting ] What formatter do you use?

### ISSUE THREAD

**Issue by lexidor** [quizlet/hammock#8]
I would like to contribute to the project and keep unrelated code untouched.
This means I need to turn off my formatter `hackfmt`.
What do you use and where do I get it?
If no formatting tool is being used, can I suggest standardizing on hackfmt?
If your are using hackfmt, what settings are you using?
You can find them in `.hhconfig` under `hackfmt.add_trailing_commas`, `hackfmt.indent_width`, `hackfmt.tabs`, and `hackfmt.line_width`.

**Comment by tyronjung-quizlet** [comment]
We use `hackfmt` at Quizlet, though I guess with settings different from yours. We can add a pre-commit hook for `hackfmt` on diff lines to resolve this.

**Comment by lexidor** [comment]
There would be no need for the pre commit hook. I can adjust mine to match yours. Settings are on a per repo basis since hhvm 3.30.5. The settings can be found in `.hhconfig`.

**Comment by turadg** [comment]
Our dev environments are on 3.27 so we have the [.hhconfig settings for `hackfmt`](https://hhvm.com/blog/2019/04/03/hhvm-4.0.4.html). We do use the `--tabs` option on the CLI.

We plan to get to 3.30 and appreciate all your improvements, so we'll see about forking a branch for 3.27 and letting master be at last 3.x release.

**Comment by lexidor** [comment]
Okay, in that case, I'll use 3.27 to hackfmt everything with the `hackfmt.tabs` setting before you branch off. This will make it easier to merge diffs / patches between two branches, since the formatting will be stable. I'll make the current master both 3.27 and 3.30 compatible in the dependency department. #12 currently only targets 3.30, but that should be something I can fix.

**Comment by lexidor** [comment]
#13 closed this issue.
