### ISSUE TITLE
[ testing ] Could we set up TravisCI?

### ISSUE THREAD

**Issue by lexidor** [quizlet/hammock#9]
This requires some github permissions that I don't have.
Feel free to copy and paste the travis.sh and travis.yml from github.com/hhvm/hhast.

For the strategy of testing, since there are so many versions between 3.30 and the nightlies, I would like to have every fourth release, plus latest and nightly. This would give us great test coverage.

**Comment by lexidor** [comment]
This would be hhvm 3.30, 4.0, 4.4, 4.8 (lts), 4.12, 4.16,... 4.32, latest , and nightly.

**Comment by tyronjung-quizlet** [comment]
Yeah this would be great, would you need Maintainer privileges for that?

**Comment by tyronjung-quizlet** [comment]
@lexidor spoke with our Trust and Safety lead at Quizlet, and he said it would be okay for you to be a Maintainer. I made you a Maintainer - let me know if that's sufficient for setting up CI.

**Comment by lexidor** [comment]
I am afraid that this is not sufficient. Adding something likes travis requires write rights. #14 adds the files, the only thing you would need to do to get it running is sign in on travis-ci.org and point TravisCI to this repo. It will figure the rest out.

**Comment by tyronjung-quizlet** [comment]
I believe Maintainer is above Write. I can add it if you're unable to proceed.

**Comment by turadg** [comment]
I merged #14 and set up https://travis-ci.org/quizlet/hammock
